# Generated by Django 6.0.4 on 2026-04-21 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solvedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedproblem',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
