DSA_ROADMAP = {
    "arrays": {
        "description": "Foundation of DSA. Master this before moving on.",
        "estimated_time": "1 week",
        "prerequisites": [],
        "easy": [
            {"title": "Two Sum", "platform": "LeetCode", "url": "https://leetcode.com/problems/two-sum/", "why_important": "Hash map pattern used everywhere"},
            {"title": "Best Time to Buy and Sell Stock", "platform": "LeetCode", "url": "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/", "why_important": "Sliding window intro"},
            {"title": "Contains Duplicate", "platform": "LeetCode", "url": "https://leetcode.com/problems/contains-duplicate/", "why_important": "Hash set basics"},
            {"title": "Maximum Subarray", "platform": "LeetCode", "url": "https://leetcode.com/problems/maximum-subarray/", "why_important": "Kadane's algorithm"},
            {"title": "Move Zeroes", "platform": "LeetCode", "url": "https://leetcode.com/problems/move-zeroes/", "why_important": "Two pointer technique"},
        ],
        "medium": [
            {"title": "Product of Array Except Self", "platform": "LeetCode", "url": "https://leetcode.com/problems/product-of-array-except-self/", "why_important": "Prefix/suffix pattern"},
            {"title": "3Sum", "platform": "LeetCode", "url": "https://leetcode.com/problems/3sum/", "why_important": "Two pointer on sorted array"},
            {"title": "Container With Most Water", "platform": "LeetCode", "url": "https://leetcode.com/problems/container-with-most-water/", "why_important": "Two pointer greedy"},
            {"title": "Subarray Sum Equals K", "platform": "LeetCode", "url": "https://leetcode.com/problems/subarray-sum-equals-k/", "why_important": "Prefix sum + hash map"},
            {"title": "Rotate Array", "platform": "LeetCode", "url": "https://leetcode.com/problems/rotate-array/", "why_important": "In-place manipulation"},
        ],
        "hard": [
            {"title": "Trapping Rain Water", "platform": "LeetCode", "url": "https://leetcode.com/problems/trapping-rain-water/", "why_important": "Classic two pointer hard"},
            {"title": "First Missing Positive", "platform": "LeetCode", "url": "https://leetcode.com/problems/first-missing-positive/", "why_important": "Index as hash map trick"},
            {"title": "Median of Two Sorted Arrays", "platform": "LeetCode", "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/", "why_important": "Binary search mastery"},
        ],
    },
    "strings": {
        "description": "String manipulation is asked in almost every interview.",
        "estimated_time": "5 days",
        "prerequisites": ["arrays"],
        "easy": [
            {"title": "Valid Palindrome", "platform": "LeetCode", "url": "https://leetcode.com/problems/valid-palindrome/", "why_important": "Two pointer on strings"},
            {"title": "Valid Anagram", "platform": "LeetCode", "url": "https://leetcode.com/problems/valid-anagram/", "why_important": "Frequency counting"},
            {"title": "Reverse String", "platform": "LeetCode", "url": "https://leetcode.com/problems/reverse-string/", "why_important": "In-place reversal"},
            {"title": "First Unique Character", "platform": "LeetCode", "url": "https://leetcode.com/problems/first-unique-character-in-a-string/", "why_important": "Hash map frequency"},
            {"title": "Longest Common Prefix", "platform": "LeetCode", "url": "https://leetcode.com/problems/longest-common-prefix/", "why_important": "String comparison basics"},
        ],
        "medium": [
            {"title": "Longest Substring Without Repeating", "platform": "LeetCode", "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/", "why_important": "Sliding window must-know"},
            {"title": "Group Anagrams", "platform": "LeetCode", "url": "https://leetcode.com/problems/group-anagrams/", "why_important": "Hash map grouping"},
            {"title": "Longest Palindromic Substring", "platform": "LeetCode", "url": "https://leetcode.com/problems/longest-palindromic-substring/", "why_important": "Expand around center"},
            {"title": "String to Integer (atoi)", "platform": "LeetCode", "url": "https://leetcode.com/problems/string-to-integer-atoi/", "why_important": "Edge case handling"},
            {"title": "Count and Say", "platform": "LeetCode", "url": "https://leetcode.com/problems/count-and-say/", "why_important": "String building pattern"},
        ],
        "hard": [
            {"title": "Minimum Window Substring", "platform": "LeetCode", "url": "https://leetcode.com/problems/minimum-window-substring/", "why_important": "Sliding window hard"},
            {"title": "Regular Expression Matching", "platform": "LeetCode", "url": "https://leetcode.com/problems/regular-expression-matching/", "why_important": "DP on strings"},
            {"title": "Wildcard Matching", "platform": "LeetCode", "url": "https://leetcode.com/problems/wildcard-matching/", "why_important": "DP pattern"},
        ],
    },
    "linked_list": {
        "description": "Pointer manipulation. Very common in FAANG interviews.",
        "estimated_time": "4 days",
        "prerequisites": ["arrays"],
        "easy": [
            {"title": "Reverse Linked List", "platform": "LeetCode", "url": "https://leetcode.com/problems/reverse-linked-list/", "why_important": "Most fundamental LL operation"},
            {"title": "Merge Two Sorted Lists", "platform": "LeetCode", "url": "https://leetcode.com/problems/merge-two-sorted-lists/", "why_important": "Pointer manipulation"},
            {"title": "Linked List Cycle", "platform": "LeetCode", "url": "https://leetcode.com/problems/linked-list-cycle/", "why_important": "Floyd's cycle detection"},
            {"title": "Middle of Linked List", "platform": "LeetCode", "url": "https://leetcode.com/problems/middle-of-the-linked-list/", "why_important": "Fast/slow pointer"},
            {"title": "Palindrome Linked List", "platform": "LeetCode", "url": "https://leetcode.com/problems/palindrome-linked-list/", "why_important": "Reverse + compare"},
        ],
        "medium": [
            {"title": "Remove Nth Node From End", "platform": "LeetCode", "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/", "why_important": "Two pointer gap technique"},
            {"title": "Add Two Numbers", "platform": "LeetCode", "url": "https://leetcode.com/problems/add-two-numbers/", "why_important": "Carry propagation"},
            {"title": "Reorder List", "platform": "LeetCode", "url": "https://leetcode.com/problems/reorder-list/", "why_important": "Find middle + reverse + merge"},
            {"title": "Sort List", "platform": "LeetCode", "url": "https://leetcode.com/problems/sort-list/", "why_important": "Merge sort on LL"},
            {"title": "Copy List with Random Pointer", "platform": "LeetCode", "url": "https://leetcode.com/problems/copy-list-with-random-pointer/", "why_important": "Hash map cloning"},
        ],
        "hard": [
            {"title": "Merge K Sorted Lists", "platform": "LeetCode", "url": "https://leetcode.com/problems/merge-k-sorted-lists/", "why_important": "Heap + linked list"},
            {"title": "Reverse Nodes in K-Group", "platform": "LeetCode", "url": "https://leetcode.com/problems/reverse-nodes-in-k-group/", "why_important": "Complex pointer reversal"},
            {"title": "LRU Cache", "platform": "LeetCode", "url": "https://leetcode.com/problems/lru-cache/", "why_important": "HashMap + DLL design"},
        ],
    },
    "trees": {
        "description": "Trees appear in 40% of FAANG interviews. Must master.",
        "estimated_time": "1 week",
        "prerequisites": ["arrays", "linked_list"],
        "easy": [
            {"title": "Maximum Depth of Binary Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/maximum-depth-of-binary-tree/", "why_important": "Basic recursion on trees"},
            {"title": "Invert Binary Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/invert-binary-tree/", "why_important": "Tree recursion pattern"},
            {"title": "Symmetric Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/symmetric-tree/", "why_important": "Mirror comparison"},
            {"title": "Path Sum", "platform": "LeetCode", "url": "https://leetcode.com/problems/path-sum/", "why_important": "Root to leaf traversal"},
            {"title": "Diameter of Binary Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/diameter-of-binary-tree/", "why_important": "DFS with global state"},
        ],
        "medium": [
            {"title": "Binary Tree Level Order Traversal", "platform": "LeetCode", "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/", "why_important": "BFS on trees"},
            {"title": "Validate Binary Search Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/validate-binary-search-tree/", "why_important": "BST property validation"},
            {"title": "Lowest Common Ancestor", "platform": "LeetCode", "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/", "why_important": "Very frequently asked"},
            {"title": "Binary Tree Right Side View", "platform": "LeetCode", "url": "https://leetcode.com/problems/binary-tree-right-side-view/", "why_important": "BFS level tracking"},
            {"title": "Construct Tree from Preorder Inorder", "platform": "LeetCode", "url": "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/", "why_important": "Tree construction"},
        ],
        "hard": [
            {"title": "Binary Tree Maximum Path Sum", "platform": "LeetCode", "url": "https://leetcode.com/problems/binary-tree-maximum-path-sum/", "why_important": "DFS with state"},
            {"title": "Serialize and Deserialize Binary Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/", "why_important": "Design + tree"},
            {"title": "Word Search II", "platform": "LeetCode", "url": "https://leetcode.com/problems/word-search-ii/", "why_important": "Trie + backtracking"},
        ],
    },
    "dynamic_programming": {
        "description": "DP is the hardest topic but appears constantly. Start easy.",
        "estimated_time": "2 weeks",
        "prerequisites": ["arrays", "strings"],
        "easy": [
            {"title": "Climbing Stairs", "platform": "LeetCode", "url": "https://leetcode.com/problems/climbing-stairs/", "why_important": "Intro to DP / Fibonacci"},
            {"title": "House Robber", "platform": "LeetCode", "url": "https://leetcode.com/problems/house-robber/", "why_important": "Classic 1D DP"},
            {"title": "Min Cost Climbing Stairs", "platform": "LeetCode", "url": "https://leetcode.com/problems/min-cost-climbing-stairs/", "why_important": "DP with choices"},
            {"title": "Pascal's Triangle", "platform": "LeetCode", "url": "https://leetcode.com/problems/pascals-triangle/", "why_important": "2D DP intro"},
            {"title": "Maximum Subarray", "platform": "LeetCode", "url": "https://leetcode.com/problems/maximum-subarray/", "why_important": "Kadane = DP"},
        ],
        "medium": [
            {"title": "Unique Paths", "platform": "LeetCode", "url": "https://leetcode.com/problems/unique-paths/", "why_important": "2D DP grid"},
            {"title": "Coin Change", "platform": "LeetCode", "url": "https://leetcode.com/problems/coin-change/", "why_important": "Unbounded knapsack"},
            {"title": "Longest Increasing Subsequence", "platform": "LeetCode", "url": "https://leetcode.com/problems/longest-increasing-subsequence/", "why_important": "Classic LIS"},
            {"title": "Word Break", "platform": "LeetCode", "url": "https://leetcode.com/problems/word-break/", "why_important": "DP + hash set"},
            {"title": "House Robber II", "platform": "LeetCode", "url": "https://leetcode.com/problems/house-robber-ii/", "why_important": "Circular DP"},
        ],
        "hard": [
            {"title": "Edit Distance", "platform": "LeetCode", "url": "https://leetcode.com/problems/edit-distance/", "why_important": "2D DP string classic"},
            {"title": "Burst Balloons", "platform": "LeetCode", "url": "https://leetcode.com/problems/burst-balloons/", "why_important": "Interval DP"},
            {"title": "Regular Expression Matching", "platform": "LeetCode", "url": "https://leetcode.com/problems/regular-expression-matching/", "why_important": "DP on patterns"},
        ],
    },
    "graphs": {
        "description": "BFS, DFS, shortest path. Essential for senior roles.",
        "estimated_time": "1 week",
        "prerequisites": ["arrays", "trees"],
        "easy": [
            {"title": "Flood Fill", "platform": "LeetCode", "url": "https://leetcode.com/problems/flood-fill/", "why_important": "BFS/DFS on grid intro"},
            {"title": "Find if Path Exists in Graph", "platform": "LeetCode", "url": "https://leetcode.com/problems/find-if-path-exists-in-graph/", "why_important": "Basic graph traversal"},
            {"title": "Number of Islands", "platform": "LeetCode", "url": "https://leetcode.com/problems/number-of-islands/", "why_important": "Most asked graph problem"},
            {"title": "Clone Graph", "platform": "LeetCode", "url": "https://leetcode.com/problems/clone-graph/", "why_important": "BFS + hash map"},
            {"title": "Course Schedule", "platform": "LeetCode", "url": "https://leetcode.com/problems/course-schedule/", "why_important": "Topological sort"},
        ],
        "medium": [
            {"title": "Pacific Atlantic Water Flow", "platform": "LeetCode", "url": "https://leetcode.com/problems/pacific-atlantic-water-flow/", "why_important": "Multi-source BFS"},
            {"title": "Number of Connected Components", "platform": "LeetCode", "url": "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/", "why_important": "Union Find"},
            {"title": "Rotting Oranges", "platform": "LeetCode", "url": "https://leetcode.com/problems/rotting-oranges/", "why_important": "Multi-source BFS timing"},
            {"title": "Word Ladder", "platform": "LeetCode", "url": "https://leetcode.com/problems/word-ladder/", "why_important": "BFS shortest path"},
            {"title": "Graph Valid Tree", "platform": "LeetCode", "url": "https://leetcode.com/problems/graph-valid-tree/", "why_important": "Cycle detection"},
        ],
        "hard": [
            {"title": "Alien Dictionary", "platform": "LeetCode", "url": "https://leetcode.com/problems/alien-dictionary/", "why_important": "Topological sort hard"},
            {"title": "Word Ladder II", "platform": "LeetCode", "url": "https://leetcode.com/problems/word-ladder-ii/", "why_important": "BFS + backtrack"},
            {"title": "Swim in Rising Water", "platform": "LeetCode", "url": "https://leetcode.com/problems/swim-in-rising-water/", "why_important": "Dijkstra variant"},
        ],
    },
    "stack_queue": {
        "description": "Stack and Queue patterns solve many interview problems elegantly.",
        "estimated_time": "3 days",
        "prerequisites": ["arrays"],
        "easy": [
            {"title": "Valid Parentheses", "platform": "LeetCode", "url": "https://leetcode.com/problems/valid-parentheses/", "why_important": "Classic stack problem"},
            {"title": "Implement Queue using Stacks", "platform": "LeetCode", "url": "https://leetcode.com/problems/implement-queue-using-stacks/", "why_important": "Stack design"},
            {"title": "Min Stack", "platform": "LeetCode", "url": "https://leetcode.com/problems/min-stack/", "why_important": "Stack with extra state"},
            {"title": "Baseball Game", "platform": "LeetCode", "url": "https://leetcode.com/problems/baseball-game/", "why_important": "Stack simulation"},
            {"title": "Backspace String Compare", "platform": "LeetCode", "url": "https://leetcode.com/problems/backspace-string-compare/", "why_important": "Stack or two pointer"},
        ],
        "medium": [
            {"title": "Daily Temperatures", "platform": "LeetCode", "url": "https://leetcode.com/problems/daily-temperatures/", "why_important": "Monotonic stack"},
            {"title": "Car Fleet", "platform": "LeetCode", "url": "https://leetcode.com/problems/car-fleet/", "why_important": "Stack simulation"},
            {"title": "Evaluate Reverse Polish Notation", "platform": "LeetCode", "url": "https://leetcode.com/problems/evaluate-reverse-polish-notation/", "why_important": "Stack expression eval"},
            {"title": "Decode String", "platform": "LeetCode", "url": "https://leetcode.com/problems/decode-string/", "why_important": "Nested stack"},
            {"title": "Asteroid Collision", "platform": "LeetCode", "url": "https://leetcode.com/problems/asteroid-collision/", "why_important": "Stack collision pattern"},
        ],
        "hard": [
            {"title": "Largest Rectangle in Histogram", "platform": "LeetCode", "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/", "why_important": "Monotonic stack hard"},
            {"title": "Maximal Rectangle", "platform": "LeetCode", "url": "https://leetcode.com/problems/maximal-rectangle/", "why_important": "Stack + DP"},
            {"title": "Basic Calculator", "platform": "LeetCode", "url": "https://leetcode.com/problems/basic-calculator/", "why_important": "Stack expression parsing"},
        ],
    },
    "binary_search": {
        "description": "Binary search is not just for sorted arrays — it's a thinking pattern.",
        "estimated_time": "3 days",
        "prerequisites": ["arrays"],
        "easy": [
            {"title": "Binary Search", "platform": "LeetCode", "url": "https://leetcode.com/problems/binary-search/", "why_important": "Template to memorize"},
            {"title": "Search Insert Position", "platform": "LeetCode", "url": "https://leetcode.com/problems/search-insert-position/", "why_important": "Lower bound pattern"},
            {"title": "Guess Number Higher or Lower", "platform": "LeetCode", "url": "https://leetcode.com/problems/guess-number-higher-or-lower/", "why_important": "Binary search on answer"},
            {"title": "First Bad Version", "platform": "LeetCode", "url": "https://leetcode.com/problems/first-bad-version/", "why_important": "Binary search on condition"},
            {"title": "Sqrt(x)", "platform": "LeetCode", "url": "https://leetcode.com/problems/sqrtx/", "why_important": "Binary search on value"},
        ],
        "medium": [
            {"title": "Search in Rotated Sorted Array", "platform": "LeetCode", "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/", "why_important": "Most asked BS medium"},
            {"title": "Find Minimum in Rotated Array", "platform": "LeetCode", "url": "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/", "why_important": "Rotation detection"},
            {"title": "Koko Eating Bananas", "platform": "LeetCode", "url": "https://leetcode.com/problems/koko-eating-bananas/", "why_important": "BS on answer space"},
            {"title": "Time Based Key-Value Store", "platform": "LeetCode", "url": "https://leetcode.com/problems/time-based-key-value-store/", "why_important": "BS in design"},
            {"title": "Search a 2D Matrix", "platform": "LeetCode", "url": "https://leetcode.com/problems/search-a-2d-matrix/", "why_important": "2D binary search"},
        ],
        "hard": [
            {"title": "Median of Two Sorted Arrays", "platform": "LeetCode", "url": "https://leetcode.com/problems/median-of-two-sorted-arrays/", "why_important": "Binary search mastery"},
            {"title": "Split Array Largest Sum", "platform": "LeetCode", "url": "https://leetcode.com/problems/split-array-largest-sum/", "why_important": "BS on answer"},
            {"title": "Find in Mountain Array", "platform": "LeetCode", "url": "https://leetcode.com/problems/find-in-mountain-array/", "why_important": "Multi-phase BS"},
        ],
    },
}